linters:
  enable:
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - typecheck
    - govet
    - varcheck
    - ineffassign
    - deadcode
    - errcheck
    - golint
    - stylecheck
    - dupl
    - depguard
    - nakedret
    - prealloc
    - gofmt
disable-all: true
