project_name: secrethub

builds:
  - &default
    id: default
    binary: "bin/secrethub"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    main: ./cmd/secrethub/main.go
    ldflags:
      - -s -w -X "github.com/secrethub/secrethub-cli/internals/secrethub.Commit={{ .ShortCommit }}" -X "github.com/secrethub/secrethub-cli/internals/secrethub.Version={{ .Version }}"
    flags:
      - -tags=production
  - <<: *default
    id: "without-bin-dir"
    binary: "secrethub"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - default
    format_overrides:
      - goos: windows
        format: zip
    files:
    - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"

brews:
  - name: secrethub-cli
    ids:
      - default
    github:
      owner: secrethub
      name: homebrew-tools
    folder: Formula

    homepage: https://secrethub.io
    description: Command-line interface for SecretHub

snapcrafts:
  - name: secrethub-cli
    builds:
      - default
    publish: true
    summary: Command-line interface for SecretHub
    description: SecretHub is a developer tool to help you keep database passwords, API tokens, and other secrets out of IT automation scripts. It enables you to securely share passwords and other secrets with your team and infrastructure.
    apps:
      secrethub:
        plugs:
          - home
          - network

scoop:
  name: secrethub-cli
  bucket:
    owner: secrethub
    name: scoop-secrethub

  homepage: https://secrethub.io
  description: Command-line interface for SecretHub

  license: Apache-2.0

nfpms:
  -
    builds:
      - without-bin-dir
    vendor: SecretHub
    homepage: https://secrethub.io
    description: CLI for using the SecretHub Secret Management Service
    maintainer: SecretHub Support <support@secrethub.io>
    license: Apache 2.0
    bindir: /usr/bin
    formats:
      - rpm
      - deb
    recommends:
      - xclip
    scripts:
      postinstall: "scripts/post-install.sh"
      postremove: "scripts/post-remove.sh"

