project_name: secrethub

builds:
  - binary: "bin/secrethub"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    main: ./cmd/secrethub/main.go
    ldflags:
      - -s -w -X main.commit={{ .ShortCommit }} -X main.version={{ .Version }}
    flags:
      - -tags=production

archive:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
  files:
  - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"

brew:
  name: secrethub-cli
  github:
    owner: secrethub
    name: homebrew-tools
  folder: Formula

  homepage: https://secrethub.io
  description: Command-line interface for SecretHub
