project_name: secrethub

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    main: ./cmd/secrethub/main.go
    ldflags:
      - -s -w -X main.commit={{ .ShortCommit }} -X main.version={{ .Version }}
    flags:
      - -tags production

archive:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    386: x86
  files:
  # Only archive the binary and LICENSE file
  - none*
  - LICENSE
