version: 2.1
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.23.8-alpine
    steps:
      - checkout
      - run: golangci-lint run
  verify-build:
    parameters:
      os:
        type: string
      arch:
        type: string
    docker:
      - image: golangci/golangci-lint:v1.23.8-alpine
    steps:
      - checkout
      - run: GOOS=<< parameters.os >> GOARCH=<< parameters.arch >> go build ./cmd/secrethub
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: make test
  verify-goreleaser:
    docker:
      - image: goreleaser/goreleaser:v0.127
    steps:
      - checkout
      - run: goreleaser check
workflows:
  version: 2
  pipeline:
    jobs:
      - lint
      - verify-build:
          matrix:
            parameters:
              arch: ["amd64", "386"]
              os: ["darwin", "linux", "windows"]
            exclude:
              - arch: 386
                os: darwin
      - test
      - verify-goreleaser
