version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: make test
  verify-goreleaser:
    docker:
      - image: goreleaser/goreleaser:v0.117
    steps:
      - checkout
      - run: goreleaser check
workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - verify-goreleaser
